services:
  # -------------------------
  # SQL Databases
  # -------------------------

  mariadb:
    image: mariadb:12.2.2
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./data/mariadb/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  
  mysql:
    image: mysql:9.6.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/mysql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:18.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./data/postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # -------------------------
  # NoSQL Databases
  # -------------------------

  cassandra:
    image: cassandra:5.0.6
    container_name: cassandra
    ports:
      - "${CASSANDRA_PORT}:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./data/cassandra/scripts/init.cql:/docker-entrypoint-initdb.d/init.cql:ro
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 40s

  clickhouse:
    image: clickhouse/clickhouse-server:26.1.3
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "${CLICKHOUSE_PORT}:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./data/clickhouse/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user=${CLICKHOUSE_USER} --password=${CLICKHOUSE_PASSWORD} --query='SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  couchbase:
    image: couchbase:community-8.0.0
    container_name: couchbase
    environment:
      COUCHBASE_ADMIN_USERNAME: ${COUCHBASE_USER}
      COUCHBASE_ADMIN_PASSWORD: ${COUCHBASE_PASSWORD}
    ports:
      - "${COUCHBASE_PORT}:8091"
    volumes:
      - couchbase_data:/opt/couchbase/var
      - ./data/couchbase/scripts/init.sh:/data/couchbase/scripts/init.sh:ro
      - ./data/couchbase/scripts/init_sdk.py:/data/couchbase/scripts/init_sdk.py:ro
    command: ["couchbase-server", "-d", "trace"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://127.0.0.1:8091/pools/default"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.0
    container_name: elasticsearch
    environment:
      - "ELASTIC_USER=${ELASTIC_USER}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "discovery.type=single-node"
    ports:
      - "${ELASTIC_PORT}:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/scripts/init.py:/data/elasticsearch/scripts/init.py
      - ./data/elasticsearch/scripts/wait-for-es.sh:/data/elasticsearch/scripts/init.sh
    command: ["sh", "/data/elasticsearch/scripts/init.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u ${ELASTIC_USER}:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health | grep '\"status\":\"green\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
 
  mongo:
    image: mongo:8.2.5
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --username ${MONGO_USER} --password ${MONGO_PASSWORD} --eval 'db.adminCommand(\"ping\")' --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.0.6
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
      - ./data/redis/scripts/init.redis:/data/init.redis
      - ./data/redis/scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
    command: ["sh", "/docker-entrypoint-initdb.d/init.sh"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # -------------------------
  # SDK Containers
  # -------------------------

  postgres-sdk:
    build:
      context: .
      dockerfile: SDK/Dockerfile.PostgreSQL
    container_name: postgres-sdk
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db_workbench
    volumes:
      - ./data/postgres/scripts:/scripts
      - postgres_data:/var/lib/postgresql/data
    working_dir: /scripts
    command: tail -f /dev/null

  couchbase-sdk:
    build:
      context: .
      dockerfile: SDK/Dockerfile.Couchbase
    container_name: couchbase-sdk
    depends_on:
      couchbase:
        condition: service_healthy
    environment:
      COUCHBASE_HOST: couchbase
      COUCHBASE_USER: ${COUCHBASE_USER}
      COUCHBASE_PASSWORD: ${COUCHBASE_PASSWORD}
      COUCHBASE_BUCKET: db_workbench
    volumes:
      - ./data/couchbase/scripts:/scripts
      - couchbase_data:/opt/couchbase/var
    working_dir: /scripts
    command: tail -f /dev/null

  # -------------------------
  # Web GUIs
  # -------------------------
  
  pgadmin:
    image: dpage/pgadmin4:9.12.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres:
        condition: service_healthy

  phpmyadmin-mysql:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: phpmyadmin-mysql
    environment:
      PMA_HOST: mysql
      PMA_DEFAULT_DB: ${MYSQL_DB}
    ports:
      - "${PHPMYADMIN_MYSQL_PORT}:80"
    depends_on:
      mysql:
        condition: service_healthy


  phpmyadmin-mariadb:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: phpmyadmin-mariadb
    environment:
      PMA_HOST: mariadb
      PMA_DEFAULT_DB: ${MARIADB_DB}
    ports:
      - "${PHPMYADMIN_MARIADB_PORT}:80"
    depends_on:
      mariadb:
        condition: service_healthy

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_DEFAULT_DB: db_workbench
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    depends_on:
      mongo:
        condition: service_healthy

  redis-insight:
    image: redislabs/redisinsight:3.0.3
    container_name: redis-insight
    ports:
      - "${REDISINSIGHT_PORT}:8001"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  mysql_data:
  mariadb_data:
  mongo_data:
  redis_data:
  cassandra_data:
  elasticsearch_data:
  clickhouse_data:
  couchbase_data: