services:
  # -------------------------
  # File-based Databases
  # -------------------------
  duckdb:
    image: duckdb/duckdb:latest
    container_name: duckdb
    volumes:
      - ./data/duckdb/db:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: ["database.duckdb"]
 
  # -------------------------
  # SQL Databases
  # -------------------------
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./data/postgres/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/mysql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./data/mariadb/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  # -------------------------
  # NoSQL Databases
  # -------------------------
  mongo:
    image: mongo:7
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
      - ./data/redis/scripts/init.redis:/data/init.redis
      - ./data/redis/scripts/init.sh:/docker-entrypoint-initdb.d/init.sh
    command: ["sh", "/docker-entrypoint-initdb.d/init.sh"]

  cassandra:
    image: cassandra:4
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER}
    ports:
      - "${CASSANDRA_PORT}:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./data/cassandra/scripts/init.cql:/data/init.cql
      - ./data/cassandra/scripts/init.sh:/data/init.sh
    command: ["sh", "/data/cassandra/scripts/init.sh"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8
    container_name: elasticsearch
    environment:
      - "ELASTIC_USER=${ELASTIC_USER}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "discovery.type=single-node"
    ports:
      - "${ELASTIC_PORT}:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/scripts/init.py:/data/elasticsearch/scripts/init.py
      - ./data/elasticsearch/scripts/wait-for-es.sh:/data/elasticsearch/scripts/init.sh
    command: ["sh", "/data/elasticsearch/scripts/init.sh"]

  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ports:
      - "${CLICKHOUSE_PORT}:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./data/clickhouse/scripts/init.sql:/data/clickhouse/scripts/init.sql
      - ./data/clickhouse/scripts/init.sh:/data/clickhouse/scripts/init.sh
    command: ["sh", "/data/clickhouse/scripts/init.sh"]

  couchbase:
    image: couchbase:7
    container_name: couchbase
    environment:
      COUCHBASE_ADMIN_USERNAME: ${COUCHBASE_USER}
      COUCHBASE_ADMIN_PASSWORD: ${COUCHBASE_PASSWORD}
    ports:
      - "${COUCHBASE_PORT}:8091"
    volumes:
      - couchbase_data:/opt/couchbase/var
      - ./data/couchbase/scripts/init.py:/data/couchbase/scripts/init.py
      - ./data/couchbase/scripts/init.sh:/data/couchbase/scripts/init.sh
    command: ["sh", "/data/couchbase/scripts/init.sh"]

  # -------------------------
  # Web GUIs
  # -------------------------
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres

  phpmyadmin-mysql:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin-mysql
    environment:
      PMA_HOST: mysql
      PMA_DEFAULT_DB: ${MYSQL_DB}
    ports:
      - "${PHPMYADMIN_MYSQL_PORT}:80"
    depends_on:
      - mysql

  phpmyadmin-mariadb:
    image: phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin-mariadb
    environment:
      PMA_HOST: mariadb
      PMA_DEFAULT_DB: ${MARIADB_DB}
    ports:
      - "${PHPMYADMIN_MARIADB_PORT}:80"
    depends_on:
      - mariadb

  mongo-express:
    image: mongo-express:1
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_DEFAULT_DB: db_workbench
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    depends_on:
      - mongo

  redis-insight:
    image: redislabs/redisinsight:2
    container_name: redis-insight
    ports:
      - "${REDISINSIGHT_PORT}:8001"
    depends_on:
      - redis

volumes:
  postgres_data:
  mysql_data:
  mariadb_data:
  mongo_data:
  redis_data:
  cassandra_data:
  elasticsearch_data:
  clickhouse_data:
  couchbase_data: