FROM python:3.11-slim

# Install Elasticsearch SDK (elasticsearch-py)
RUN pip install --no-cache-dir elasticsearch

# Set the working directory to /scripts
WORKDIR /scripts

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]