FROM python:3.11-slim

# Install Redis SDK (redis-py)
RUN pip install --no-cache-dir redis

# Set the working directory to /scripts
WORKDIR /scripts

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]