FROM python:3.11-slim

# Prevent Python from writing .pyc files & enable unbuffered logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install necessary Python libraries, including the requests library
RUN pip install --no-cache-dir elasticsearch requests

# Set working directory
WORKDIR /scripts

# Keep container alive
CMD ["tail", "-f", "/dev/null"]