FROM python:3.11-slim

# Install Cassandra SDK (cassandra-driver)
RUN pip install --no-cache-dir cassandra-driver

# Set the working directory to /scripts
WORKDIR /scripts

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]