FROM python:3.11-slim

# Prevent Python from writing .pyc files & enable unbuffered logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install Cassandra Python driver
RUN pip install --no-cache-dir cassandra-driver

# Set working directory
WORKDIR /scripts

# Keep container alive (Makefile runs init_sdk.py manually)
CMD ["tail", "-f", "/dev/null"]