FROM python:3.11-slim

# Install MongoDB SDK (pymongo)
RUN pip install --no-cache-dir pymongo

# Set the working directory to /scripts
WORKDIR /scripts

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]