FROM python:3.11-slim

# Install ClickHouse SDK (clickhouse-driver)
RUN pip install --no-cache-dir clickhouse-driver

# Set the working directory to /scripts
WORKDIR /scripts

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]