FROM python:3.11-slim

# Install CockroachDB SDK (psycopg2)
RUN apt-get update && \
    apt-get install -y libpq-dev && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir psycopg2-binary

# Set the working directory to /scripts
WORKDIR /scripts

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]