FROM python:3.11-slim

# Install MySQL SDK (mysql-connector-python)
RUN pip install --no-cache-dir mysql-connector-python

# Set the working directory to /scripts
WORKDIR /scripts

# Default command to keep the container running
CMD ["tail", "-f", "/dev/null"]